We've been creating numpy arrays using the np.array function and passing a list of elements to it as an argument. Here are some examples:

In [2]:
import numpy as np
A = np.array([1, 2, 3])
print(A)

[1 2 3]


or like this:

In [3]:
b = [[3.6, 2.9], [.9, 7.2]]
B = np.array(b)
print(B)

[[3.6 2.9]
 [0.9 7.2]]


We can use the array function also with tuples:

In [5]:
c = (4, 6, 9)

C = np.array(c)

print(C)

[4 6 9]


But sometimes we need arrays containing specific data, like constant values, increasing or decreasing values, uniformly spaced numbers, random numbers and so on. To this end we can use quite a lot of functions besides the basic np.array function we've been using so far. Let's have a look at some of the most frequently used ones.

If we need an array where all the elements have constant values, we can use one of the following functions:

- np.zeros - if all the elements should be zeros
- np.ones - if we need an array of ones
- np.full - if we need a constant value different than 0 or 1
- the fill method - if we want to fill an array that already exists with some constant values

Here's how we can use these functions:

In [6]:
# a 3-dimensional array (3x5x2) filled with zeros
D = np.zeros((3, 5, 2))
print(D)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [7]:
# a 1-dimensional array of 25 ones
E = np.ones(25)
print(E)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1.]


In [9]:
# a 2-dimensional array (7x3) where each element is set to 5.7
F = np.full((7, 3), 5.7)
print(F)

[[5.7 5.7 5.7]
 [5.7 5.7 5.7]
 [5.7 5.7 5.7]
 [5.7 5.7 5.7]
 [5.7 5.7 5.7]
 [5.7 5.7 5.7]
 [5.7 5.7 5.7]]


We can also create an empty array using the np.empty function and then fill it with constant values. The empty function creates an array with uninitialized elements. Let's create one, check the data it contains and then fill it with elements set to 5. By the way, the data in the empty array may be different than presented here, it's accidental.

In [12]:
G = np.empty((4, 5))
print(G)
G.fill(5)
print(G)

[[ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000e+000]
 [-1.08648420e-310  0.00000000e+000  0.00000000e+000  0.00000000e+000
   0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 -2.06429988e-310
   0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000 -1.84700751e-310  4.67296746e-307
   1.69121096e-306]]
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


There are also functions that create arrays filled with zeros, ones, other constant values or unitialized values based on other arrays, so they take the shape and data type after other arrays but the elements they contain are different. The functions are called np.zeros_like, np.ones_like, np.full_like and np.empty_like. Let's have a look at them in action:

In [34]:
# Here's a 2-dimensional array of ints and a 1-dimensional array of floats.
H = np.array([[4, 3], [2, 8]])
I = np.array([.9, 1.2, 3.2, 2.2, 4., 5.2, 5.4, .7])

print(H)
print(I)

# Now let's create some arrays that have the same shapes and data types as the two arrays above.
# First two arrays that should be filled with zeros.
print(np.zeros_like(H))
print(np.zeros_like(I))

# Then two arrays that should be filled with ones.
print(np.ones_like(H))
print(np.ones_like(I))

# Finally two arrays that should be filled with 3.
print(np.full_like(H, 3))
print(np.full_like(I, 3))


[[4 3]
 [2 8]]
[0.9 1.2 3.2 2.2 4.  5.2 5.4 0.7]
[[0 0]
 [0 0]]
[0. 0. 0. 0. 0. 0. 0. 0.]
[[1 1]
 [1 1]]
[1. 1. 1. 1. 1. 1. 1. 1.]
[[3 3]
 [3 3]]
[3. 3. 3. 3. 3. 3. 3. 3.]


EXERCISE

Create an 2-dimensional 5x4 zero-filled array and then another array with all elements set to 2.5. Use one of the _like functions mentioned above.

Print the two arrays out.


SOLUTION

In [35]:
X = np.zeros((5, 4))
print(X)

Y = np.full_like(X, 2.5)
print(Y)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5]
 [2.5 2.5 2.5 2.5]]
