If we want to create an array with incremental or decremental values, we can use the np.arange function, which works very much like the built-in range function in Python, or the np.linspace function. Here's how we can use them:

In [13]:
# the np.arange function takes up to 3 arguments, just like the range function: start value, end value (not included) 
# and optionally the step.

# Here it is with 1 argument:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# Here it is with 2 arguments:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [15]:
# and with 3 arguments:
np.arange(100, 0, -5)

array([100,  95,  90,  85,  80,  75,  70,  65,  60,  55,  50,  45,  40,
        35,  30,  25,  20,  15,  10,   5])

In [16]:
# The linspace function also takes 3 arguments, but here the end value is included. Besides, the third argument determines
# the total number of elements in the array:
np.linspace(5, 10, 8)

array([ 5.        ,  5.71428571,  6.42857143,  7.14285714,  7.85714286,
        8.57142857,  9.28571429, 10.        ])

Here we have 8 elements uniformly spaced between 5 and 10. If we don't want the end value to be included, we can set the endpoint keyword argument to False:

In [17]:
np.linspace(5, 10, 8, endpoint = False)

array([5.   , 5.625, 6.25 , 6.875, 7.5  , 8.125, 8.75 , 9.375])

We can also create arrays with logarithmic sequences. The function we need for that is np.logspace. It works just like np.linspace, which means it takes 3 arguments: from, to, and how many elements, but the values are distributed logarithmically. By default it uses the base-10 logarithm but you can change it by setting the base keyword argument. Some examples:

In [19]:
# 10 elements logarithmically spaced (in base 10) between 1(10**0) and 1000 (10**3):
np.logspace(0, 3, 10)

array([   1.        ,    2.15443469,    4.64158883,   10.        ,
         21.5443469 ,   46.41588834,  100.        ,  215.443469  ,
        464.15888336, 1000.        ])

We can also change the endpoint argument to False and change the base, let's say to 2. This will give us 10 values logarithmically spaced (in base 2) between 1 (2**0) and 8 (2**3), 8 not being included:

In [20]:
np.logspace(0, 3, 10, endpoint = False, base = 2)

array([1.        , 1.23114441, 1.51571657, 1.86606598, 2.29739671,
       2.82842712, 3.48220225, 4.28709385, 5.27803164, 6.49801917])

EXERCISE

Create an array of 20 elements, uniformly spaced between 1 and 100, 100 not being included. Use an attribute of the ndarray class to make sure there are indeed 20 elements.


SOLUTION

In [25]:
X = np.linspace(0, 100, 20, endpoint = False)
print(X)
print(X.size)

[ 0.  5. 10. 15. 20. 25. 30. 35. 40. 45. 50. 55. 60. 65. 70. 75. 80. 85.
 90. 95.]
20
