There is another useful way of creating numpy arrays. We can create arrays from functions. To this end we use the np.fromfunction function.

This function creates an array by executing a function over each coordinate, so the number of parameters the function takes must be equal to the number of dimensions. Let's start with something simple, a 1-dimensional array:

In [5]:
import numpy as np

# First we need a function that takes 1 parameter, because it's going to be a 1-dimensional array:
def f(x):
    return x

# Now let's create an array from this function. The np.fromfunction function takes the function as the first argument,
# then the shape of the array as the second argument, and optionally we can also pass the dtype as the third argument.
A = np.fromfunction(f, (7,), dtype = int)
A

array([0, 1, 2, 3, 4, 5, 6])

So, here we have a 1-dimensional array with 7 elements. This is because the passed the shape tuple (7,) to the function. The values are the consecutive values returned by the f function.

Now, let's modify our function a bit to see the difference:

In [6]:
def f(x):
    return 5 * x + 0.5

B = np.fromfunction(f, (7,))
B

array([ 0.5,  5.5, 10.5, 15.5, 20.5, 25.5, 30.5])

Now the function returns:
5 * 0 + 0.5 = 0.5 for the first element,
5 * 1 + 0.5 = 5.5 for the second element and so on.

We often use lambda functions instead of functions defined using the def keyword. Here's how we could rewrite our last example:

In [7]:
C = np.fromfunction(lambda x: 5 * x + 0.5, (7,))
C

array([ 0.5,  5.5, 10.5, 15.5, 20.5, 25.5, 30.5])

or, if we prefer to keep our code clear and readable, we could do it like so:

In [8]:
f = lambda x: 5 * x + 0.5
D = np.fromfunction(f, (7,))
D

array([ 0.5,  5.5, 10.5, 15.5, 20.5, 25.5, 30.5])

OK, and now let's have a look at multidimensional arrays. Let's create a 2-dimesional 3x4 array:

In [10]:
# Here's the function we'll use. Now we need 2 parameters because there are two dimensions.
f = lambda x, y: 2 * x + y

# Now we're ready to create the array.
E = np.fromfunction(f, (3, 4), dtype = int)
E


array([[0, 1, 2, 3],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

So, what we get is:

in the first row:
2 * 0 + 0 = 0
2 * 0 + 1 = 1
2 * 0 + 2 = 2
2 * 0 + 3 = 3

so the value of x is 0 for the first row. The value of x will increase along the axis, so in the consecutive rows, whereas the value of y increases along the second axis (or dimension).

Now, in the second row we'll have:
2 * 1 + 0 = 2
2 * 1 + 1 = 3
2 * 1 + 2 = 4
2 * 1 + 3 = 5

and so on.

EXERCISE

Create a multiplication table that looks like this:

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

So, your task is to create a 2-dimensional 10 x 10 array where the elements are the products of the elements in the first row and column. This table should be created from a function that you must first create. Remember to start with 1, not 0 and to set the data type to integers.

SOLUTION

In [12]:
f = lambda x, y: (x + 1) * (y + 1)
M = np.fromfunction(f, (10, 10), dtype = int)
M

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])