Indexing and slicing 1-dimensional arrays is pretty straightforward. It works just like with Python lists. Here are some examples:

In [1]:
import numpy as np

# let's create an array
A = np.array([2, 4, 6, 3, 5, 7])
A

array([2, 4, 6, 3, 5, 7])

In [2]:
# get the first element
A[0]

2

In [3]:
# get the last element
A[-1]

7

In [4]:
# slice from index 2 to index 5 (exclusive)
A[2:5]

array([6, 3, 5])

In [5]:
# slice from the beginning to index 5 (exclusive)
A[:5]

array([2, 4, 6, 3, 5])

In [6]:
# slice from index 3 to the end
A[3:]

array([3, 5, 7])

In [7]:
# get all the elements
A[:]

array([2, 4, 6, 3, 5, 7])

In [9]:
# slice from index 1 to index 5 (exclusive) with step 2, so every other element
A[1:5:2]

array([4, 3])

Now let's have a look at multidimensional arrays. First let's create one from a function:

In [17]:
f = lambda x, y: x + 10 + 10 * y
B = np.fromfunction(f, (6, 5), dtype = int)
B

array([[10, 20, 30, 40, 50],
       [11, 21, 31, 41, 51],
       [12, 22, 32, 42, 52],
       [13, 23, 33, 43, 53],
       [14, 24, 34, 44, 54],
       [15, 25, 35, 45, 55]])

The first way of indexing such arrays is just like Python nested lists, so using two indices in square brackets like so:

In [18]:
# let's select the element in the third row (so index 2) and the fifth column (index 4)
B[2][4]

52

This works, but it's inefficient because it creates a temporary intermediate array (B[2] in this case) which is then indexed with the second index. A more efficient way is to put all the indices in one pair of square brackets:

In [19]:
B[2, 4]

52

When slicing multidimensional arrays we also separate the ranges for each dimension by commas inside one pair of square brackets. Here's our B array again and now let's slice it in a couple of different ways:

In [20]:
B

array([[10, 20, 30, 40, 50],
       [11, 21, 31, 41, 51],
       [12, 22, 32, 42, 52],
       [13, 23, 33, 43, 53],
       [14, 24, 34, 44, 54],
       [15, 25, 35, 45, 55]])

In [21]:
# let's select the rows from 1 to 3 and the columns from 2 to the end:
B[1:4, 2:]

array([[31, 41, 51],
       [32, 42, 52],
       [33, 43, 53]])

As you can see, the first range is for the first dimension, or the rows, the second range is for the second dimension, or the columns.

Some more examples:

In [22]:
# let's select the rows from the beginning to 2 and the columns from 1 to 2:
B[:3, 1:3]

array([[20, 30],
       [21, 31],
       [22, 32]])

In [23]:
# Now we want all the rows and all the columns:
B[:, :]

array([[10, 20, 30, 40, 50],
       [11, 21, 31, 41, 51],
       [12, 22, 32, 42, 52],
       [13, 23, 33, 43, 53],
       [14, 24, 34, 44, 54],
       [15, 25, 35, 45, 55]])

In [24]:
# If we skip the indices for some dimensions, they are automatically set to :, so the whole dimension is selected. 
# Let's select the rows from 1 to 2 and all the columns.
B[1:3]

array([[11, 21, 31, 41, 51],
       [12, 22, 32, 42, 52]])

In [25]:
# We can also use the step to skip some rows or columns. Now we want every other row and the columns from the beginning to 2:
B[::2, :3]

array([[10, 20, 30],
       [12, 22, 32],
       [14, 24, 34]])

In [26]:
# and now every other row and every other column:
B[::2, ::2]

array([[10, 30, 50],
       [12, 32, 52],
       [14, 34, 54]])

EXERCISE

Using the np.array function and passing a nested list to it, create a 4x4 array with elements from 1 to 16 (consecutive numbers in 4 rows). Then slice it so as to obtain all even numbers from it, and then one more time to obtain all odd numbers from it. Print the original array and the two slices.

SOLUTION

In [28]:
X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

print(X)

X_even = X[::, 1::2]
X_odd = X[::, ::2]

print(X_even)
print(X_odd)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]
