When slicing numpy arrays we create views on the original arrays. So, we are working on the same original data, which means that if we change some data in a view, it will also be changed in the original array. Have a look:

In [3]:
import numpy as np

A = np.fromfunction(lambda x, y: 10 * (x + 1) * (y + 1), (4, 4), dtype = int)
A

array([[ 10,  20,  30,  40],
       [ 20,  40,  60,  80],
       [ 30,  60,  90, 120],
       [ 40,  80, 120, 160]])

In [4]:
# Now let's slice the array
B = A[::2, ::2]
B

array([[10, 30],
       [30, 90]])

In [5]:
# Now B is a view. Let's change the first element.
B[0, 0] = 0

# This change takes place in the original array, so it's visible in both the view and the array.
B

array([[ 0, 30],
       [30, 90]])

In [6]:
A

array([[  0,  20,  30,  40],
       [ 20,  40,  60,  80],
       [ 30,  60,  90, 120],
       [ 40,  80, 120, 160]])

In [7]:
# Now let's create another slice:
C = A[:, :3]
C

array([[  0,  20,  30],
       [ 20,  40,  60],
       [ 30,  60,  90],
       [ 40,  80, 120]])

In [8]:
# Let's set all elements in the C view to 1
C[:, :] = 1
C

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [9]:
# And now let's print the original array:
A

array([[  1,   1,   1,  40],
       [  1,   1,   1,  80],
       [  1,   1,   1, 120],
       [  1,   1,   1, 160]])

If you want to create an independent copy instead of a view, you should use the copy method:

In [10]:
# Let's recreate our A array.
A = np.fromfunction(lambda x, y: 10 * (x + 1) * (y + 1), (4, 4), dtype = int)
A

array([[ 10,  20,  30,  40],
       [ 20,  40,  60,  80],
       [ 30,  60,  90, 120],
       [ 40,  80, 120, 160]])

In [12]:
# Let's create a slice as a copy:
B = A[:3, :3].copy()
B

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [13]:
# Let's set all the elements in the B copy to 1:
B[:, :] = 1
B

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
# Now the original A array remains untouched.
A

array([[ 10,  20,  30,  40],
       [ 20,  40,  60,  80],
       [ 30,  60,  90, 120],
       [ 40,  80, 120, 160]])

Alternatively you can use the np.copy function:

In [15]:
C = np.copy(A[:3, :3])
C

array([[10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [16]:
C[:, :] = 5
C

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [17]:
A

array([[ 10,  20,  30,  40],
       [ 20,  40,  60,  80],
       [ 30,  60,  90, 120],
       [ 40,  80, 120, 160]])

EXERCISE

Using an appropriate numpy function create a 5 x 8 array of ones. Then create a view that contains all the internal elements (so all the elements except those which are in the first and last row and column). Set all the values in the view to 0. Print the original array, the view before changing the values, the view after changing the values and the original array after changing the values.

SOLUTION

In [21]:
X = np.ones((5, 8))
print(X)
Y = X[1:-1, 1:-1]
print(Y)
Y[:, :] = 0
print(Y)
print(X)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
