numpy arrays may be indexed with boolean expression. All elements are selected for which the value of the boolean expression evaluates to True. Here's a simple example:

In [1]:
import numpy as np

# Let's create an array
A = np.array([4, 12, 7, 11, 9, 22, 6, 42, 61])

# Now let's select only the elements which are less than 10.
# First let's see for which elements this is True:
A < 10

array([ True, False,  True, False,  True, False,  True, False, False])

In [2]:
# And now let's use the expression as the index.
A[A < 10]

array([4, 7, 9, 6])

In [5]:
# How about elements that are divisible by 11?
A[A % 11 == 0]

array([11, 22])

In [7]:
# And now let's create a multidimensional array.
B = np.fromfunction(lambda x, y: (3 - x) * (y + 3), (6, 6), dtype = int)
B

array([[  9,  12,  15,  18,  21,  24],
       [  6,   8,  10,  12,  14,  16],
       [  3,   4,   5,   6,   7,   8],
       [  0,   0,   0,   0,   0,   0],
       [ -3,  -4,  -5,  -6,  -7,  -8],
       [ -6,  -8, -10, -12, -14, -16]])

In [9]:
# Let's filter out all the negative and zero values:
B[B > 0]

array([ 9, 12, 15, 18, 21, 24,  6,  8, 10, 12, 14, 16,  3,  4,  5,  6,  7,
        8])

As you can see, we get a 1-dimensional array with all the elements for which the boolean expression was True. One thing to remember about fancy indexing and boolean indexing is that the new arrays are independent arrays, not views.

EXERCISE

Create a 1-dimensional X array with 100 numbers evenly spaced between -2 and 2 (inclusive). Use boolean indexing to create a new array with all the elements from the X array which raised to the power of 2 are greater than 3.

SOLUTION

In [10]:
X = np.linspace?

In [11]:
X = np.linspace(-2, 2, 100)
X

array([-2.        , -1.95959596, -1.91919192, -1.87878788, -1.83838384,
       -1.7979798 , -1.75757576, -1.71717172, -1.67676768, -1.63636364,
       -1.5959596 , -1.55555556, -1.51515152, -1.47474747, -1.43434343,
       -1.39393939, -1.35353535, -1.31313131, -1.27272727, -1.23232323,
       -1.19191919, -1.15151515, -1.11111111, -1.07070707, -1.03030303,
       -0.98989899, -0.94949495, -0.90909091, -0.86868687, -0.82828283,
       -0.78787879, -0.74747475, -0.70707071, -0.66666667, -0.62626263,
       -0.58585859, -0.54545455, -0.50505051, -0.46464646, -0.42424242,
       -0.38383838, -0.34343434, -0.3030303 , -0.26262626, -0.22222222,
       -0.18181818, -0.14141414, -0.1010101 , -0.06060606, -0.02020202,
        0.02020202,  0.06060606,  0.1010101 ,  0.14141414,  0.18181818,
        0.22222222,  0.26262626,  0.3030303 ,  0.34343434,  0.38383838,
        0.42424242,  0.46464646,  0.50505051,  0.54545455,  0.58585859,
        0.62626263,  0.66666667,  0.70707071,  0.74747475,  0.78

In [12]:
X[X ** 2 > 3]

array([-2.        , -1.95959596, -1.91919192, -1.87878788, -1.83838384,
       -1.7979798 , -1.75757576,  1.75757576,  1.7979798 ,  1.83838384,
        1.87878788,  1.91919192,  1.95959596,  2.        ])