Sometimes you may want to reshape or resize your array, like for example make a matrix array out of several vectors or the other way around, turn a vector to a matrix. numpy offers quite a bunch of functions that will let you do just that. Usually there are also corresponding methods in the ndarray class. So, suppose we have a one-dimensional array that we want to reshape into a matrix:

In [1]:
import numpy as np

# Here's our 1-dimensional array
A = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Let's use the np.reshape function to make a 4 x 2 matrix out of it.
np.reshape(A, (4, 2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [2]:
# Alternatively, we could use the reshape method:
A.reshape((4, 2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

When reshaping arrays like that we have to make sure that the number of elements will match the new shape. Otherwise we'll get an error like here:

In [3]:
# We can't reshape the A array to a 3 x 3 matrix because we have not enough elements.
A.reshape((3, 3))

ValueError: cannot reshape array of size 8 into shape (3,3)

We can also reshape a multidimensional array to a vector. One way to do it is by means of the aforementioned reshape function. Another way is to use the ravel function. Have a look.

In [4]:
# Here's our 2-dimensional array
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Let's use the reshape function to turn it to a 1-dimensional array.
np.reshape(B, (9,))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# Here's how we can do it with the np.ravel function or its corresponding ravel method.
np.ravel(B)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

The reshape and ravel functions create views. If we need a copy, we can use the flatten method:

In [8]:
B.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

It's also possible to add new empty dimensions or axes. To do that we use the np.newaxis keyword as an index:

In [10]:
# Here we have a 1-dimensional array:
C = np.arange(4)
C

array([0, 1, 2, 3])

In [11]:
# Let's add one more direction to the array:
D = C[:, np.newaxis]
D

array([[0],
       [1],
       [2],
       [3]])

In [19]:
# We can also use np.newaxis as the first index, depending on where we want the axis to be added.
E = C[np.newaxis, :]
E

array([[0, 1, 2, 3]])

EXERCISE

Using the np.arange function create a 1-dimensional array with numbers from 1 to 12. Then use the reshape method to reshape it into a 2-dimensional array in all possible ways.

SOLUTION

In [18]:
X = np.arange(1, 13)

print(X)
print(X.reshape((1, 12)))  # this works like [np.newaxis, :]
print(X.reshape((2, 6)))
print(X.reshape((3, 4)))
print(X.reshape((4, 3)))
print(X.reshape((6, 2)))
print(X.reshape((12, 1)))  # this works like [:, np.newaxis]


[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
