Sometimes you may want to merge arrays into bigger arrays, like for example merge a couple of vectors into a matrix. To this end we can use the np.vstack and np.hstack functions, which stack the arrays vertically and horizontally respectively. Here's how the functions work:

In [3]:
import numpy as np

# First let's create two vectors.
A = np.array([1, 2, 3, 4])
B = np.array([10, 20, 30, 40])

# Now let's stack them vertically. The vstack function takes a tuple with the arrays to merge as an argument.
np.vstack((A, B))

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [9]:
# In the above example the vector arrays became the rows of the newly created matrix array.
# Let's see how the hstack function works.
np.hstack((A, B))

array([ 1,  2,  3,  4, 10, 20, 30, 40])

In [10]:
# Well, it merges the two arrays horizontally into another 1-dimensional array. But what if we want the vector arrays
# to become the columns of the newly created array? Well, we have to add another axis to each array, which we can do using
# the np.newaxis keyword.
np.hstack((A[:, np.newaxis], B[:, np.newaxis]))

array([[ 1, 10],
       [ 2, 20],
       [ 3, 30],
       [ 4, 40]])

Naturally, the number of dimensions doesn't have to be changed when two arrays are stacked. Let's have a look at the following 2-dimensional arrays merged together:

In [13]:
# We can chain functions. Let's create a vector array and reshape it into a matrix array.
C = np.arange(1, 13).reshape((3, 4))
C

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
D = np.arange(21, 33).reshape((3, 4))
D

array([[21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [15]:
# Now let's stack the two matrices vertically:
np.vstack((C, D))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [16]:
# and horizontally:
np.hstack((C, D))

array([[ 1,  2,  3,  4, 21, 22, 23, 24],
       [ 5,  6,  7,  8, 25, 26, 27, 28],
       [ 9, 10, 11, 12, 29, 30, 31, 32]])

In [18]:
# Alternatively we can use the np.concatenate function, for which we have to specify along which axis the merging
# should take place:
# So, let's merge the arrays vertically:
np.concatenate((C, D), axis = 0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [21, 22, 23, 24],
       [25, 26, 27, 28],
       [29, 30, 31, 32]])

In [19]:
# and horizontally:
np.concatenate((C, D), axis = 1)

array([[ 1,  2,  3,  4, 21, 22, 23, 24],
       [ 5,  6,  7,  8, 25, 26, 27, 28],
       [ 9, 10, 11, 12, 29, 30, 31, 32]])

EXERCISE

Using the np.arange and np.reshape functions create three 4 x 3 arrays X, Y and Z and stack them all vertically. The X array should contain values from 1 to 12, Y from 11 to 22 and Z from 21 to 32.

SOLUTION

In [20]:
X = np.arange(1, 13).reshape((4, 3))
Y = np.arange(11, 23).reshape((4, 3))
Z = np.arange(21, 33).reshape((4, 3))
np.vstack((X, Y, Z))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19],
       [20, 21, 22],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32]])