You can perform all the basic arithmetic operations on numpy arrays. The operations are performed elementwise, so it is important that the arrays have the same sizes and shapes. If they don't, it's still sometimes possible, but this will be discussed in the next lecture. Now let's concentrate on equal-sized arrays.

Let's first create 2 arrays, on which we'll then perform a couple of arithmetic operations.

In [1]:
import numpy as np

# Here are the arrays:
A = np.arange(1, 7).reshape(3, 2)
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [18]:
B = np.array([[7, 2], [4, 5], [8, 3]])
B

array([[7, 2],
       [4, 5],
       [8, 3]])

In [19]:
# And now the operations. First addition:
A + B

array([[ 8,  4],
       [ 7,  9],
       [13,  9]])

In [20]:
# Watch how the arrays are added elementwise. Now subtraction:
A - B

array([[-6,  0],
       [-1, -1],
       [-3,  3]])

In [21]:
# multiplication
A * B

array([[ 7,  4],
       [12, 20],
       [40, 18]])

Note that this is different than matrix multiplication. Here the elements are multiplied elementwise.

In [22]:
# Now true division:
A / B

array([[0.14285714, 1.        ],
       [0.75      , 0.8       ],
       [0.625     , 2.        ]])

As you can see, the data type may be promoted if the result can't be represented within its bounds.

In [23]:
# and floor division:
A // B

array([[0, 1],
       [0, 0],
       [0, 2]], dtype=int32)

In [24]:
# exponentiation
A ** B

array([[     1,      4],
       [    81,   1024],
       [390625,    216]], dtype=int32)

In [25]:
# modulus
A % B

array([[1, 0],
       [3, 4],
       [5, 0]], dtype=int32)

It's also possible to perform operations on arrays and scalars. Then the operation is performed on the scalar and each element of the array. Here are some examples:

In [14]:
# Here's our A array again:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
# Now let's add 10 to it:
A + 10

array([[11, 12],
       [13, 14],
       [15, 16]])

In [26]:
# How about raising each element to the power of 3?
A ** 3

array([[  1,   8],
       [ 27,  64],
       [125, 216]], dtype=int32)

and so on. 

When we perform an operation on 2 arrays, a new array with the result is created in memory. Instead, we may want to assign the resulting array back to the first original array. You can use the regular Python syntax, with augmented assignment operators being the preferable way to go. Some examples:

In [27]:
# Here's our A array again:
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
# Let's add another array to it inplace:
C = np.array([[1, 2], [5, 3], [6, 3]])
C

array([[1, 2],
       [5, 3],
       [6, 3]])

In [29]:
A = A + C
A

array([[ 2,  4],
       [ 8,  7],
       [11,  9]])

In [31]:
# Now let's subtract 2 from the A array (the modified one) and assign the result back to A. 
# We'll use an augmented assignment operator:
A -= 2
A

array([[0, 2],
       [6, 5],
       [9, 7]])

EXERCISE

Here are two arrays. Perform all the operations on a piece of paper, without using your computer first and then check out if you were right.

X = np.array([4, 2, 6, 3])
Y = np.array([3, 1, 4, 5])

operations:

1) X + X * Y
2) 2 * (Y - X)
3) X ** 2 - Y

SOLUTION

In [32]:
X = np.array([4, 2, 6, 3])
Y = np.array([3, 1, 4, 5])
X + X * Y

array([16,  4, 30, 18])

In [33]:
2 * (Y - X)

array([-2, -2, -4,  4])

In [34]:
X ** 2 - Y

array([13,  3, 32,  4])