Given two numpy arrays, we can compare them elementwise. What we get is a new array with boolean values. We can use all the standard comparison operators like ==, !=, >, <, >=, <=. If the shapes of the arrays are different, all the broadcasting rules apply. Some examples:

In [2]:
import numpy as np

# Let's create two simple arrays that we are then going to compare:
A = np.array([1, 3, 6, 9, 12])
B = np.array([2, 4, 6, 8, 12])

# Let's check them for equality first:
A == B

array([False, False,  True, False,  True])

In [3]:
# As you can see we have True at those indices where the elements are indeed equal.

# Now, inequality.
A != B

array([ True,  True, False,  True, False])

In [4]:
# Now let's use all the variations of greater than and less than operators.
A > B

array([False, False, False,  True, False])

In [5]:
A < B

array([ True,  True, False, False, False])

In [6]:
A >= B

array([False, False,  True,  True,  True])

In [7]:
A <= B

array([ True,  True,  True, False,  True])

We can also combine the comparison operators with the aggregation functions np.any and np.all. Let's see if each element in the A array is greater than its counterpart in the B array:

In [8]:
np.all(A > B)

False

In [9]:
# Well it isn't. So, maybe there is at least one element in A with the same value as in B?
np.any(A == B)

True

EXERCISE

Here we have two arrays:

X = np.array([[5, 6], [4, 1]])
Y = np.array([[3, 7], [8, 2]])

Write a program that for each row and each column in turn checks whether all the values in X are less than in Y, so, in particular it should answer the following questions:

1) Are all elements in the first row of X less than in Y?
2) Are all elements in the second row of X less than in Y?
3) Are all elements in the first column of X less than in Y?
4) Are all elements in the second column of X less than in Y?

Hint: use slicing.

SOLUTION

In [10]:
X = np.array([[5, 6], [4, 1]])
X

array([[5, 6],
       [4, 1]])

In [11]:
Y = np.array([[3, 7], [8, 2]])
Y

array([[3, 7],
       [8, 2]])

In [12]:
# first row
np.all(X[0, :] < Y[0, :])

False

In [14]:
# second row
np.all(X[1, :] < Y[1, :])

True

In [15]:
# first column
np.all(X[:, 0] < Y[:, 0])

False

In [16]:
# second column
np.all(X[:, 1] < Y[:, 1])

True