We can pick values from arrays based on a condition. To this end we can use the functions np.where, np.select and np.choose. Let's have a look at them now one by one.

First, the np.where function. It takes 3 arrays as parameters, the first of which is a boolean array, which is actually the condition array. The function creates a new array picking elements from the two arrays passed as the second and third argument. Wherever the value in the condition array is True, the corresponding element from the second array is selected, wherever it's False, an element from the third array is selected. Have a look:

In [1]:
import numpy as np

# First let's create the two arrays from which elements will be selected:
A = np.array([1, 2, 3, 4, 5, 6])
B = np.array([10, 20, 30, 40, 50, 60])

# now the condition array. Let's pick the odd numbers from the first array.
cond = A % 2 != 0
cond

array([ True, False,  True, False,  True, False])

In [2]:
# And now we can use the condition array to select all elements from A, for which the value in cond is True and the elements
# from B for which the value in cond is False:
np.where(cond, A, B)

array([ 1, 20,  3, 40,  5, 60])

In [3]:
# We can also create the arrays on the fly. Here's an example:
C = np.arange(1, 11)
C

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
# Now, we want the squares of the elements that are less than 6 and square roots of the other elements:
np.where(C < 6, C ** 2, np.sqrt(C))

array([ 1.        ,  4.        ,  9.        , 16.        , 25.        ,
        2.44948974,  2.64575131,  2.82842712,  3.        ,  3.16227766])

The next function is np.select. This function takes two parameters: a list of boolean condition arrays and a list of arrays. In the resulting array we get elements from the array for which the corresponding condition is met. Here's an example.

In [12]:
# Let's define an array
D = np.array([-3, -1, 0, 2, 4])

# and now let's select the following:
# - the absolute values (first array) of negative elements (first condition), so 3 and 1
# - the squares (second array) of elements less than 3 (second condition), so 0 and 4
# - the quintuples (third array) of elements greater than 3 (third condition), so 20
np.select([D < 0, D <= 3, D > 3], [np.abs(D), D ** 2, 5 * D])


array([ 3,  1,  0,  4, 20])

The next function is np.choose. It takes two parameters: a list of indices and a list of arrays. The indices determine from which array an element should be taken. Here's an example.

In [13]:
# Let's create three arrays:
E = np.arange(1, 11)
E

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
F = np.arange(101, 111)
F

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [15]:
G = np.arange(1001, 1011)
G

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010])

In [17]:
# And now suppose we want the first two elements from the first array, then five elements from the second array
# then again one element from the first array and finally two elements from the last array. Here's how we can
# do it using the indices of the arrays in the list of arrays:
np.choose([0, 0, 1, 1, 1, 1, 1, 0, 2, 2], [E, F, G])

array([   1,    2,  103,  104,  105,  106,  107,    8, 1009, 1010])

EXERCISE

Create an array of 50 evenly spaced numbers between -100 and 50 and call it X. Set the dtype to int, so that the numbers are truncated down to integers. Then create an array of square roots of the absolute values of all the negative elements in X, squares of all the positive elements less 20 and the constant 100 for all positive numbers equal to or greater than 20.


SOLUTION

In [23]:
X = np.linspace(-100, 50, 50, dtype = int)    # np.linspace(-10, 5) would also work because the default value of elements is 50
X

array([-100,  -96,  -93,  -90,  -87,  -84,  -81,  -78,  -75,  -72,  -69,
        -66,  -63,  -60,  -57,  -54,  -51,  -47,  -44,  -41,  -38,  -35,
        -32,  -29,  -26,  -23,  -20,  -17,  -14,  -11,   -8,   -5,   -2,
          1,    4,    7,   10,   13,   16,   19,   22,   25,   28,   31,
         34,   37,   40,   43,   46,   50])

In [27]:
np.select([X < 0, X < 20, X >= 20], [np.sqrt(np.abs(X)), X ** 2, 100])

array([ 10.        ,   9.79795897,   9.64365076,   9.48683298,
         9.32737905,   9.16515139,   9.        ,   8.83176087,
         8.66025404,   8.48528137,   8.30662386,   8.1240384 ,
         7.93725393,   7.74596669,   7.54983444,   7.34846923,
         7.14142843,   6.8556546 ,   6.63324958,   6.40312424,
         6.164414  ,   5.91607978,   5.65685425,   5.38516481,
         5.09901951,   4.79583152,   4.47213595,   4.12310563,
         3.74165739,   3.31662479,   2.82842712,   2.23606798,
         1.41421356,   1.        ,  16.        ,  49.        ,
       100.        , 169.        , 256.        , 361.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        , 100.        , 100.        ,
       100.        , 100.        ])