numpy offers us a couple of logical functions, in particular np.logical_and, np.logical_or, np.logical_xor and np.logical_not. Let's start with the last one. We use the np.logical_not function to elementwise invert an array. Zero is interpreted as False, any nonzero value as True.

In [3]:
import numpy as np

# Let's first create an array of numbers:
A = np.array([-2, 0, 4, 2, 9, 0, 3])

# Now let's invert it:
np.logical_not(A)

array([False,  True, False, False, False,  True, False])

As you can see in the output, the values are inverted: we have True for zero values and False for nonzero values.

In [4]:
# Another example:
np.logical_not(A <= 0)

array([False, False,  True,  True,  True, False,  True])

Now we have False for the values for which the condition A <= 0 is met and True for the ones for which it's not met. This is because the values are inverted.

The other functions work elementwise on two arrays. Let's create the two arrays then to demonstrate on them how the logical functions work.

In [11]:
# We'll need two arrays:
B = np.array([True, False, True, False])
C = np.array([True, True, False, False])

# Let's start with the np.logical_and function. We'll have True only at indices at which there was True in both arrays.
np.logical_and(B, C)

array([ True, False, False, False])

In [12]:
# The np.logical_or function returns True if there is True in at least one of the arrays.
np.logical_or(B, C)

array([ True,  True,  True, False])

In [13]:
# np.logical_xor returns True if there is True in one array, but not in both.
np.logical_xor(B, C)

array([False,  True,  True, False])

EXERCISE

Try to figure out on a piece of paper what the resulting array will be if the following logical functions are performed on the X and Y arrays. Then check it out.

Here are the two arrays:

X = np.array([1, 0, 0, 1])
Y = np.array([0, 0, 1, 0])

And here's the code. We'll assign the functions to variables for clarity.

n = np.logical_not
a = np.logical_and
r = np.logical_or
x = np.logical_xor

x(r(n(X), a(X, Y)), Y)

SOLUTION

In [17]:
X = np.array([1, 0, 0, 1])
Y = np.array([0, 0, 1, 0])

n = np.logical_not
a = np.logical_and
r = np.logical_or
x = np.logical_xor

x(r(n(X), a(X, Y)), Y)

array([False,  True, False, False])