numpy provides a vast functionality for random numbers. The function we're going to need are in the np.random module. There are lots of them, let's just have a look at some.

In [4]:
import numpy as np

# Let's start with np.random.random, which returns uniformly distributed floats between 0 and 1 (but not including 1)
np.random.random()

0.6637812970161031

In [46]:
# We can pass an integer to the function. This will create a 1-dimensional array with as many elements as the integer.
np.random.random(6)

array([0.02306243, 0.52477466, 0.39986097, 0.04666566, 0.97375552,
       0.23277134])

In [24]:
# We can also pass the shape of an array to create a multidimensional array with random values:
np.random.random((5, 3))

array([[0.61324446, 0.92798142, 0.71759513],
       [0.32386582, 0.35608486, 0.67874322],
       [0.5662589 , 0.27354633, 0.06695727],
       [0.49163763, 0.21702818, 0.81779189],
       [0.80740763, 0.79961316, 0.86711246]])

In [9]:
# If you need a random integer, use np.random.randint. Let's find a random number between 3 and 6, the latter being exclusive.
np.random.randint(3, 6)

5

In [19]:
# If you pass just one value, you'll get a random integer between 0 and that value (also exclusive)
np.random.randint(3)

2

In [20]:
# And now let's create a 4 x 5 array of integers between 10 and 20:
np.random.randint(10, 21, (4, 5))

array([[20, 14, 19, 11, 18],
       [15, 20, 17, 13, 10],
       [17, 20, 13, 20, 14],
       [18, 13, 16, 11, 11]])

In [26]:
# The np.random.rand function is used if you need an array of floats between 0 and 1 (exclusive) of a given shape.
# You just pass the dimensions along all the axes as arguments. Now, let's create a 3-dimensional array of floats:
np.random.rand(4, 2, 3)

array([[[0.55597754, 0.44381172, 0.16455908],
        [0.00231127, 0.15472743, 0.99403601]],

       [[0.652406  , 0.36579183, 0.12818295],
        [0.84744186, 0.17374748, 0.92257383]],

       [[0.84129489, 0.79710847, 0.90442657],
        [0.41670601, 0.09303319, 0.25975573]],

       [[0.05928313, 0.63373176, 0.6587817 ],
        [0.35615422, 0.23543988, 0.57931781]]])

In [38]:
# Now let's use the np.random.randint function again. We could use any of the other functions as well. If we execute the code 
# multiple times, the result may be different each time. Here's a 1-dimensional array of 12 random integers between 1 and 100.
# Let's call the function 5 times. The results will be different each time.
print(np.random.randint(1, 101, 12))
print(np.random.randint(1, 101, 12))
print(np.random.randint(1, 101, 12))
print(np.random.randint(1, 101, 12))
print(np.random.randint(1, 101, 12))

[ 94 100  82  97  90   7  62  27   6   1  87   3]
[53 42 45 95 15 53 66 62 80 25 53 17]
[29 56 86 78 92 74 90 32 55 66 43 90]
[54 80 98 49 22 87 37 38 51  1 93 28]
[94 44 88 59 83 27 97 53 87 11 15 35]


In [44]:
# If you want the numbers to be the same each time, you have to reseed the generator. To this end you should use the function
# np.random.seed with an integer argument. Here we'll reseed the generator with two different integers. Watch the results.

np.random.seed(31)
print(np.random.randint(1, 101, 12))
np.random.seed(42)
print(np.random.randint(1, 101, 12))
np.random.seed(31)
print(np.random.randint(1, 101, 12))
np.random.seed(42)
print(np.random.randint(1, 101, 12))
np.random.seed(42)
print(np.random.randint(1, 101, 12))

[83 88 17 99 24 59 29 94 93 43 47  7]
[ 52  93  15  72  61  21  83  87  75  75  88 100]
[83 88 17 99 24 59 29 94 93 43 47  7]
[ 52  93  15  72  61  21  83  87  75  75  88 100]
[ 52  93  15  72  61  21  83  87  75  75  88 100]


EXERCISE

The np.random.random function returns floats between 0 and 1. Use it along with some other necessary operations so that you create a 1-dimensional array of 10 random floats between 5 and 6 (exclusive).

SOLUTION

In [47]:
5 + np.random.random(10)

array([5.09060643, 5.61838601, 5.38246199, 5.98323089, 5.46676289,
       5.85994041, 5.68030754, 5.45049925, 5.01326496, 5.94220176])