In Python if we need a collection where all elements are unique, we use sets. In numpy we can also make all the elements in an array unique and then we can work on it like on a set. In order to make an array unique, we use the np.unique function. It also sorts the array. Here's an example.

In [3]:
import numpy as np

# First let's create an array with repetitive values.
A = np.array([7, 4, 4, 2, 7, 1, 7, 4, 3])

# And now let's make a set of it:
B = np.unique(A)
B

array([1, 2, 3, 4, 7])

In [6]:
# Naturally we can also create a set array like this in one step:
C = np.unique([5, 2, 3, 9, 2, 3, 1, 5, 2])
C

array([1, 2, 3, 5, 9])

We can check whether the elements of an array are enclosed in another array. We can use the function np.in1d and pass the two arrays to it.

In [12]:
# First let's check whether array B is enclosed in array C. This works elementwise, so we'll get True for the elements of B
# which are in C and False for those which aren't.
np.in1d(B, C)

array([ True,  True,  True, False, False])

There are also functions for typical set operations: 

In [14]:
# If we want to find the intersection of two arrays, we can use the np.intersect1d function. 
# This will return the elements which are in both arrays. 

# Let's see which elements are in both B and C:
np.intersect1d(B, C)

array([1, 2, 3])

In [15]:
# We can use the np.setdiff1d function to find the difference of two sets. The difference contains all the elements which are
# in the first array but not in the other. So, the difference of B and C is:

np.setdiff1d(B, C)

array([4, 7])

In [16]:
# and the difference of C and B is:
np.setdiff1d(C, B)

array([5, 9])

In [17]:
# Finally, to find the union of two sets, so the elements which can be found in at least one of the sets, 
# we can use the function np.union1d:
np.union1d(B, C)

array([1, 2, 3, 4, 5, 7, 9])

EXERCISE

Here we have two arrays:

X = np.array([2, 3, 6])
Y = np.array([1, 2, 3, 4, 5, 6, 7])

Find out, using appropriate numpy functions, if set X is a subset of Y.

Hint: set a is a subset of set b if all elements of a are in b.

SOLUTION

In [18]:
X = np.array([2, 3, 6])
Y = np.array([1, 2, 3, 4, 5, 6, 7])

np.all(np.in1d(X, Y))

True