Most of the functions we have been talking about up to now work on an element by element basis. Some, like the aggregation functions, either reduce arrays to scalars or flatten them to arrays of fewer dimensions. But there are also functions in numpy that operate on arrays as a whole rather than elementwise and return transformed arrays of the same size, although not necessarily of the same shape.

The first function we're going to talk about is np.transpose. There also exists a method in the ndarray class with the same name and we can also use a special name, just capital T, without parentheses. 

The function reverses all the axes. If used on a 2-dimensional array, it just exchanges the rows and the columns. Here are some examples.

In [3]:
import numpy as np

# Here's a matrix array
A = np.random.randint(1, 20, (4, 3))
A

array([[ 1, 11, 13],
       [ 4,  1,  5],
       [ 6, 16,  6],
       [ 4,  9,  1]])

In [4]:
# Let's now transpose it. First using the transpose function.
np.transpose(A)

array([[ 1,  4,  6,  4],
       [11,  1, 16,  9],
       [13,  5,  6,  1]])

In [5]:
# As you can see the rows and the columns have been swapped. We can do the same using the transpose method:
A.transpose()

array([[ 1,  4,  6,  4],
       [11,  1, 16,  9],
       [13,  5,  6,  1]])

In [7]:
# or its special name, T:
A.T

array([[ 1,  4,  6,  4],
       [11,  1, 16,  9],
       [13,  5,  6,  1]])

In [10]:
# Then we have the np.fliplr (for flip left-right) and np.flipud (for flip up-down) functions that we can use to
# flip an array horizontally or vertically. First let's print the A array again so that we can see it better.
A

array([[ 1, 11, 13],
       [ 4,  1,  5],
       [ 6, 16,  6],
       [ 4,  9,  1]])

In [11]:
# And now let's see how these two functions work. First horizontally:
np.fliplr(A)

array([[13, 11,  1],
       [ 5,  1,  4],
       [ 6, 16,  6],
       [ 1,  9,  4]])

In [12]:
# and now vertically:
np.flipud(A)

array([[ 4,  9,  1],
       [ 6, 16,  6],
       [ 4,  1,  5],
       [ 1, 11, 13]])

In [16]:
# Another function is np.sort. It sorts the elements of an array along a specified axis. Let's print the A array again:
A

array([[ 1, 11, 13],
       [ 4,  1,  5],
       [ 6, 16,  6],
       [ 4,  9,  1]])

In [17]:
# And now let's sort it along the last axis, which is the default.
np.sort(A)

array([[ 1, 11, 13],
       [ 1,  4,  5],
       [ 6,  6, 16],
       [ 1,  4,  9]])

In [18]:
# And now let's specify another axis.
np.sort(A, axis = 0)

array([[ 1,  1,  1],
       [ 4,  9,  5],
       [ 4, 11,  6],
       [ 6, 16, 13]])

In [21]:
# The np.sort function returns a new array. If what we need is inplace sorting, we should use the sort method:
A.sort()
A

array([[ 1, 11, 13],
       [ 1,  4,  5],
       [ 6,  6, 16],
       [ 1,  4,  9]])

EXERCISE

Create a 2 x 4 array of containing the integers: 7, 2, 3, 7, 4, 9, 0, 2 and then transpose it. In the original transposed array sort the elements in each column.

SOLUTION

In [45]:
X = np.array([7, 2, 3, 7, 4, 9, 0, 2]).reshape(2, 4).T
X

array([[7, 4],
       [2, 9],
       [3, 0],
       [7, 2]])

In [46]:
X.sort(axis = 0)
X

array([[2, 0],
       [3, 2],
       [7, 4],
       [7, 9]])