If we multiply two matrix arrays, the multiplication is performed elementwise, which is not what real matrix multiplication is. Let's see again how multiplication works:

In [1]:
import numpy as np

# Let's create two vector arrays first and multiply them using the standard multiplication operator:
A = np.array([3, 8, 2])
B = np.array([4, 6, 1])
A * B

array([12, 48,  2])

In [2]:
# If instead we want to calculate the dot product of the two vectors, we should use the np.dot function:
np.dot(A, B)   

62

In [11]:
# Now let's create matrix arrays and multiply them using the standard multiplication operator. This will work elementwise.
C = np.array([[2, 5, 9], [3, 4, 1], [2, 1, 1]])
C

array([[2, 5, 9],
       [3, 4, 1],
       [2, 1, 1]])

In [9]:
D = np.array([[2, 1, 4], [1, 6, 5], [3, 4, 0]])
D

array([[2, 1, 4],
       [1, 6, 5],
       [3, 4, 0]])

In [12]:
C * D

array([[ 4,  5, 36],
       [ 3, 24,  5],
       [ 6,  4,  0]])

In [13]:
# Again, we use the np.dot function to calculate the dot product:
np.dot(C, D)

array([[36, 68, 33],
       [13, 31, 32],
       [ 8, 12, 13]])

In [15]:
# Matrix multiplication is only possible if the number of columns of the first matrix is the same as the number of rows
# of the second matrix.
# Let's create two other arrays and multiply them using the np.dot function:
E = np.array([[2, 5, 1], [4, 3, 8]])
E

array([[2, 5, 1],
       [4, 3, 8]])

In [19]:
F = np.array([[2, 6], [3, 5], [0, 4]])
F        

array([[2, 6],
       [3, 5],
       [0, 4]])

Now, the first matrix has 3 columns and the second matrix has 3 rows, so we can calculate their dot product.

Just a quick reminder on matrix multiplication. In the example above we have the following two matrices:
E = [2, 5, 1], or symbolically [e11, e12, e13]
    [4, 3, 8],                 [e21, e22, e23]
                   

and 

F = [2, 6], or symbolically [f11, f12]
    [3, 5],                 [f21, f22]
    [0, 4]                  [f31, f32]
    


And here's how the dot product is calculated:

[e11*f11 + e12*f21 + e13*f31 = 2*2 + 5*3 + 1*0 = 19, e11*f12 + e12*f22 + e13*f32 = 2*6 + 5*5 + 1*4 = 41]
[e21*f11 + e22*f21 + e23*f31 = 4*2 + 3*3 + 8*0 + 17, e21*f12 + e22*f22 + e23*f32 = 4*6 + 3*5 + 8*4 = 71]


In [20]:
# We should get the same result using the np.dot function:
np.dot(E, F)

array([[19, 41],
       [17, 71]])

In [22]:
# Alternatively, we can use the @ operator for matrix multiplication. It also returns the dot product of two matrices:
E @ F

array([[19, 41],
       [17, 71]])

EXERCISE

Calculate the dot product of the following to matrices on a piece of paper and then check your solution using the np.dot function and the @ operator.

Here are the two matrices:

X = np.array([10, 5, 2])
Y = np.array([[4, 3, 2, 5], [7, 10, 0, 1], [3, 3, 2, 6]])

SOLUTION

In [24]:
X = np.array([10, 5, 2])
Y = np.array([[4, 3, 2, 5], [7, 10, 0, 1], [3, 3, 2, 6]])

np.dot(X, Y)

array([81, 86, 24, 67])

In [25]:
X @ Y

array([81, 86, 24, 67])